title: Backtick
logo: /images/icon-500.png
description: Website for the Backtick Chrome extension
plugins:
    - jekyll-relative-links
relative_links:
    enabled: true
    collections: true
include:
    - README.md
    - privacy-policy.md
remote_theme: pmarsceill/just-the-docs
