title: Backtick
description: Website for the Backtick Chrome extension
url: 'https://backtick.zachbrogan.com'
logo: /images/logo.png
search_enabled: false
plugins:
    - jekyll-relative-links
relative_links:
    enabled: true
    collections: true
exclude:
    - README.md
remote_theme: pmarsceill/just-the-docs
